### ISSUE TITLE
Portfolio: Wrong dependency to jdk8

### ISSUE THREAD

**Issue by ulrichbayer** [SebRut/chocolatey-packages#13]
Hi,
Portfolio's nuget file contains a wrong dependency:
`<dependency id="jdk8" />`
This dependency is not needed since the PortfolioPerformance-distro zip file includes its own JRE.
It would be great if you could remove it since being forced to have various JDK versions installed only causes problems in my experience.

best,
Ulrich

**Comment by SebRut** [comment]
Hey! I removed the `jdk8` dependency, please tell me if this breaks something on the next  update.
